apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: external-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: secret-store
  target:
    name: ssm-parameters
    creationPolicy: Owner
  dataFrom:
  - find:
      path: /kubernetes
      name:
        regexp: merge-freeze
    rewrite:
    - regexp:
        source: "/kubernetes/merge-freeze/(.*)"
        target: "$1"
