apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: merge-freeze-test
spec:
  ingressClassName: 'kong'
  rules:
    - host: 'mergefreeze-test.procurify.com'
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: merge-freeze-web
                port:
                  number: 3100
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: merge-freeze-server
                port:
                  number: 3200
          - path: /auth
            pathType: Prefix
            backend:
              service:
                name: merge-freeze-server
                port:
                  number: 3200
          - path: /slack
            pathType: Prefix
            backend:
              service:
                name: merge-freeze-server
                port:
                  number: 3200
          - path: /github
            pathType: Prefix
            backend:
              service:
                name: merge-freeze-server
                port:
                  number: 3200
          - path: /status
            pathType: Prefix
            backend:
              service:
                name: merge-freeze-server
                port:
                  number: 3200
